[package]
name = "xeranova_game"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.1"
bevy_ecs_tilemap = "0.16.0"
noise = "0.9.0"
rand = "0.9.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
